# Generated by Django 3.2.8 on 2021-10-31 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriiPicturi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_categorie', models.CharField(max_length=100)),
                ('descriere_categorie', models.TextField()),
                ('imagine_categorie', models.ImageField(upload_to='TeenyTiny/images/')),
            ],
            options={
                'verbose_name_plural': 'Categorii de picturi',
            },
        ),
        migrations.CreateModel(
            name='Picturi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_pictura', models.CharField(max_length=100)),
                ('descriere_pictura', models.TextField()),
                ('imagine_pictura', models.ImageField(upload_to='TeenyTiny/images/')),
                ('categorie_pictura', models.ForeignKey(default='Nealocat', on_delete=django.db.models.deletion.SET_DEFAULT, to='TeenyTiny.categoriipicturi')),
            ],
            options={
                'verbose_name_plural': 'Picturi',
            },
        ),
    ]
