# Generated by Django 3.2.8 on 2021-11-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeenyTiny', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField(max_length=3500)),
                ('date_and_time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Emailuri primite',
            },
        ),
    ]
