# Generated by Django 3.2.8 on 2021-11-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeenyTiny', '0002_receivedemails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceivedEmails',
        ),
    ]
