# Generated by Django 3.2.8 on 2021-12-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeenyTiny', '0005_alter_receivedemails_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedemails',
            name='subject',
            field=models.CharField(default='nimic', max_length=35),
            preserve_default=False,
        ),
    ]
