# Generated by Django 3.2.8 on 2021-12-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeenyTiny', '0006_receivedemails_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedemails',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
