# Generated by Django 3.2.8 on 2021-12-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeenyTiny', '0007_alter_receivedemails_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
                ('imagine', models.ImageField(upload_to='TeenyTiny/images/')),
                ('arime_imagine', models.CharField(default='1654px(latime) X 2339px (inaltime) jpg', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='categoriipicturi',
            name='marime_imagine',
            field=models.CharField(default='1597px X 1597px circle png', max_length=100),
        ),
        migrations.AddField(
            model_name='picturi',
            name='marime_imagine',
            field=models.CharField(default='1654px(latime) X 2339px (inaltime) jpg', max_length=100),
        ),
    ]
