# Generated by Django 3.2.8 on 2021-12-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeenyTiny', '0008_auto_20211214_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About us'},
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='arime_imagine',
            new_name='marime_imagine',
        ),
    ]
